# Generated by Django 4.1.3 on 2022-12-13 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('div_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('usn', models.CharField(max_length=255)),
                ('img1', models.ImageField(upload_to='')),
                ('img3', models.ImageField(upload_to='')),
                ('img2', models.ImageField(upload_to='')),
                ('img4', models.ImageField(upload_to='')),
                ('img5', models.ImageField(upload_to='')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.division')),
            ],
        ),
    ]
