# Generated by Django 4.1.3 on 2022-12-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img1',
            field=models.ImageField(upload_to='studentsphotos/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img2',
            field=models.ImageField(upload_to='studentsphotos/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img3',
            field=models.ImageField(upload_to='studentsphotos/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img4',
            field=models.ImageField(upload_to='studentsphotos/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='img5',
            field=models.ImageField(upload_to='studentsphotos/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.related.ForeignKey>/<django.db.models.fields.CharField>/'),
        ),
    ]
