# Generated by Django 4.1.3 on 2022-12-13 09:01

from django.db import migrations, models
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_img1_alter_student_img2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img1',
            field=models.ImageField(upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='img2',
            field=models.ImageField(upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='img3',
            field=models.ImageField(upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='img4',
            field=models.ImageField(upload_to=student.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='student',
            name='img5',
            field=models.ImageField(upload_to=student.models.user_directory_path),
        ),
    ]
