# Generated by Django 4.1.3 on 2023-02-27 14:27

from django.db import migrations, models
import django.db.models.deletion
import student.models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_tempfiletest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelTrained',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.FileField(upload_to=student.models.model_directory_path)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.division')),
            ],
        ),
        migrations.CreateModel(
            name='Classrooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cno', models.CharField(max_length=3)),
                ('cip', models.CharField(max_length=255)),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.department')),
                ('div', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.division')),
            ],
        ),
    ]
